### ISSUE TITLE
[hub-mirror] pull emailservice:v0.3.5

### ISSUE THREAD

**Issue by darshanhuang1** [darshanhuang1/hub-mirror#2]
{
"hub-mirror": [
"gcr.io/google-samples/microservices-demo/emailservice:v0.3.5"
]
}

**Comment by togettoyou** [comment]
貌似 Fork 后 Actions 不会自动触发，稍等，我看看

**Comment by togettoyou** [comment]
你试试 `Settings`-`Actions`-`General`-`Actions permissions` 选择 `Allow all actions` 并 `Save`

**Comment by darshanhuang1** [comment]
缺省就是这样的配置

**Comment by togettoyou** [comment]
你做了什么操作，现在可以了
